version: "3.8"
services:
  web:
    image: falantasw/nt-tool:0.0.1
    # build:
    #   context: ./
    pull_policy: if_not_present
    ports:
      - 8050:8050
    volumes:
      - ./input:/code/input
      - ./output:/code/output
      